# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 577d274f26932b1fcb4081c9389d3ebb000cd4a115cd301600ab3f39449c2517bc63f5a4c1c04225f9dcae4fc47c06d674f1f600b32e381c68eba10c02b6a902

test:
  secret_key_base: 41dd3dec9b4574a7b9b0ac863043531120489768a50663e6f3f620cc25b2acf7824efd3e10a7456539d6694de2bee71b098ae6d5468520f6469a0d0534937a9b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
